# Generated by Django 5.1 on 2024-10-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0002_alter_buy_bookingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='orderstatus',
            field=models.BooleanField(default=True),
        ),
    ]
